# Generated by Django 4.2.6 on 2023-10-12 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tsc_stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('store_code', models.CharField(max_length=4)),
                ('store_createdate', models.DateTimeField(default=datetime.datetime(2023, 10, 12, 18, 47, 13, 501310))),
            ],
        ),
    ]
