# Generated by Django 4.2.6 on 2023-10-13 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='photo_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='images/')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 10, 13, 13, 22, 4, 951347))),
            ],
        ),
        migrations.AlterField(
            model_name='tsc_stores',
            name='store_createdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 13, 13, 22, 4, 950351)),
        ),
    ]
