# Generated by Django 4.2.6 on 2023-10-13 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsc', '0002_photo_upload_alter_tsc_stores_store_createdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand_names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 10, 13, 17, 40, 51, 577094))),
            ],
        ),
        migrations.AlterField(
            model_name='photo_upload',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 13, 17, 40, 51, 577094)),
        ),
        migrations.AlterField(
            model_name='tsc_stores',
            name='store_createdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 13, 17, 40, 51, 577094)),
        ),
    ]
