# Generated by Django 4.2.6 on 2023-10-26 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsc', '0005_author_book_publisher_alter_brand_names_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='store',
            name='books',
        ),
        migrations.AlterField(
            model_name='brand_names',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 18, 51, 41, 162730)),
        ),
        migrations.AlterField(
            model_name='photo_upload',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 18, 51, 41, 162730)),
        ),
        migrations.AlterField(
            model_name='tsc_stores',
            name='store_createdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 18, 51, 41, 162730)),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
